### ISSUE TITLE
Mapbox dependency

### ISSUE THREAD

**Issue by mskzo** [geoman-io/maplibre-geoman#8]
`  
node_modules/@geoman-io/maplibre-geoman-free/dist/maplibre-geoman.es.js:4:20:
      4 │ import * as yl from "mapbox-gl";
        ╵                     ~
`

The last version of geoman-maplibre is including mapbox instead of maplibre.

**Comment by mscno** [comment]
Hi mskzo, yes we are working on adding compatibility to mapbox. However this should not be exposed in the library. Thanks for pointing this out so that we can fix it.

**Comment by zxwild** [comment]
> The last version of geoman-maplibre is including mapbox instead of maplibre.

Fixed in the last commits.

The plugin now supports two base maps: MapLibre and Mapbox (very alpha stage).

But it requires avoiding any base map-specific imports across the whole project, for example, it's impossible to use TS types from Mapbox and MapLibre in places other than the MapAdapter.

So we have to re-invent some types like map events, etc.

**Comment by jchapuis** [comment]
👋 hello still getting 

```
   node_modules/@geoman-io/maplibre-geoman-free/dist/index-DTETc3Nq.js:6:19:
      6 │ import * as g from "mapbox-gl";
        ╵                    ~~~~~~~~~~~
```        

with version `0.2.12` is this expected? cheers

**Comment by zxwild** [comment]
It's a side effect of new way of TS types exporting, it's fixed in the latest commits, will be available soon.
As a quick-fix "mapbox-gl" could be installed: `npm install --save mapbox-gl`.

Pros: In the latest commits all geoman types will be available without exceptions.

**Comment by mscno** [comment]
Solved
